Name:           kubeconform
Version:        0.8.0
Release:        5%{?dist}
Summary:        Fast Kubernetes manifests validator with Custom Resource support

%global debug_package %{nil}

License:        Apache-2.0
URL:            https://github.com/yannh/kubeconform
Source0:        %{url}/archive/refs/tags/v%{version}.tar.gz#/%{name}-%{version}.tar.gz

BuildRequires:  git-core
BuildRequires:  go
Requires:       glibc

ExclusiveArch:  x86_64

%description
kubeconform validates Kubernetes manifests against upstream JSON schemas and
supports Custom Resources.

%prep
%autosetup -n %{name}-%{version}
%if 0%{?fedora} < 44
go mod edit -go=1.25
%endif
go mod download

%build
cd cmd/%{name}
export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export CGO_LDFLAGS="${LDFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"

go build -ldflags "-w -s -linkmode=external" .

%check
go test ./...

%install
install -Dpm0755 cmd/%{name}/%{name} %{buildroot}%{_bindir}/%{name}
install -Dpm0644 Readme.md %{buildroot}%{_docdir}/%{name}/Readme.md
install -Dpm0644 LICENSE %{buildroot}%{_licensedir}/%{name}/LICENSE

%files
%{_bindir}/%{name}
%doc %{_docdir}/%{name}/Readme.md
%license %{_licensedir}/%{name}/LICENSE

%changelog
* Fri Jun 12 2026 kritag <kristian.tagesen@tieto.com> - 0.8.0-5
- Build 0.8.0 on all Fedora releases; patch go.mod to go 1.25 on Fedora < 44
  to work around GOTOOLCHAIN=local with Go 1.25

* Thu Jun 11 2026 kritag <kristian.tagesen@tieto.com> - 0.8.0-1
- Update to 0.8.0; Fedora 44+ only due to Go >= 1.26 requirement

* Thu Jun 11 2026 kritag <kristian.tagesen@tieto.com> - 0.7.0-3
- Revert to 0.7.0; 0.8.0 requires Go >= 1.26, unavailable in Fedora 43

* Wed Apr 08 2026 Codex <codex@example.invalid> - 0.7.0-2
- Disable autogenerated debug subpackages to avoid empty debugsource output

* Wed Apr 08 2026 Codex <codex@example.invalid> - 0.7.0-1
- Initial package
